version: '2'
services:
  python:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./:/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - PYTHONUNBUFFERED=0
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports: 
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/myx.cnf
