version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # login to docker hub
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t servicerocket/mysql2snowflake:latest snowflake/

     # deploy the image
     - run: docker push servicerocket/mysql2snowflake:latest

     # build the application image
     - run: docker build -t servicerocket/mysql2redshift:latest redshift/

     # deploy the image
     - run: docker push servicerocket/mysql2redshift:latest

     # build the application image
     - run: docker build -t servicerocket/mysql2bigquery:latest bigquery/

     # deploy the image
     - run: docker push servicerocket/mysql2bigquery:latest